language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

script:
  - $PIP install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      $PIP install twine
      python -m twine upload wheelhouse/pcst_fast-*.whl
    fi

env:
  global:
    - CIBW_BEFORE_BUILD_MACOS="pip install pybind11"
    - CIBW_BEFORE_BUILD_WINDOWS="pip install pybind11"
    - CIBW_BEFORE_BUILD_LINUX="pip install pybind11"
    # - CIBW_TEST_COMMAND="make pcst_fast_test && ./pcst_fast_test"
    - TWINE_USERNAME=zfrenchee
      # Note: TWINE_PASSWORD is set in Travis settings
