matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx

script:
  - pip3 install cibuildwheel==0.6.0
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/pcst_fast-*.whl
    fi

env:
  global:
    - CIBW_BEFORE_BUILD="{pip} install pybind11"
    - CIBW_SKIP=cp26-*
    # - CIBW_TEST_COMMAND="make pcst_fast_test && ./pcst_fast_test"
    - TWINE_USERNAME=zfrenchee
      # Note: TWINE_PASSWORD is set in Travis settings
